### ISSUE TITLE
"SSL SUPPORT" link broken

### ISSUE THREAD

**Issue by abraxxa** [Perl-Toolchain-Gang/HTTP-Tiny#3]
`See ["SSL SUPPORT"](https://metacpan.org/pod/HTTP::Tiny#SSL-SUPPORT) for more on the verify_SSL and SSL_options attributes.`
Should be something like:
`See ["TLS/SSL SUPPORT"](https://metacpan.org/pod/HTTP::Tiny#TLS/SSL-SUPPORT) for more on the verify_SSL and SSL_options attributes.`
Not sure if the forward slash needs to be escaped in POD.

**Comment by haarg** [comment]
Fixed by 23509209917cd9ef7e948eb3c800b775e927b31a
